name: .NET Deploy

on:
  push:
    branches: [ "main" ]
    
permissions:
  contents: read
  actions: read
  checks: write

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './Waterloo.Consumer' # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '9.0.x' # set this to the dotnet version to use

jobs:
  build-api:
    name: Build API
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
         dotnet-version: '9.x'

    - name: Build & Publish API
      run: dotnet publish ./Waterloo/Waterloo.csproj -c Release -o ./output/API

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: Waterloo.API
        path: ./output/API
  
  build-and-deploy-consumer:
    name: Build Consumer
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4321AC17EA6C4BEC9195B870271EF803 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8B099ED176054B82A8592DFDB8631F60 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_321E033950F948098839465233AFF470 }}

      - name: 'Run Azure Functions Action'
        uses: azure/functions-action@v2
        id: fa
        with:
          app-name: 'waterloo-consumer-ping'
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
          enable-oryx-build: true
          build-preset: 'functions'

  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    needs: [ build-api ]
    permissions:
      id-token: write
      contents: read

    if: github.event_name == 'push'
    steps:
      - name:  Download Waterloo.API artifact
        uses: actions/download-artifact@v4
        with:
           name: Waterloo.API
           path: ./output/API
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E4AE3DC18E7341BBBD1C8F376BF14073 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A203C6D3812F4FABA252821AAC688860 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_80547AAC20D2412D8AA5F3C1A1B3E4D3 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'waterloo-ping'
          slot-name: 'Production'
          package: ./output/API