name: .NET Deploy

on:
  push:
    branches: [ "main" ]
    
permissions:
  contents: read
  actions: read
  checks: write

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './Waterloo.Consumer' # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '9.0.x' # set this to the dotnet version to use

jobs:
  build-api:
    name: Build API
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
         dotnet-version: '9.x'

    - name: Build & Publish API
      run: dotnet publish ./Waterloo/Waterloo.csproj -c Release -o ./output/API

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: Waterloo.API
        path: ./output/API
  
  build-and-deploy-consumer:
    name: Build Consumer (Windows)
    runs-on: windows-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: pwsh
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_758118A4F62742769D0877A2997FB2AE }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_83FD417CCE7E4AF78ED091BE86D7F367 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_CD093012B3A54940AAF206D65932E4AA }}

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'waterloo-consumer'
          slot-name: 'Production'
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'

  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    needs: [ build-api ]
    permissions:
      id-token: write
      contents: read

    if: github.event_name == 'push'
    steps:
      - name:  Download Waterloo.API artifact
        uses: actions/download-artifact@v4
        with:
           name: Waterloo.API
           path: ./output/API
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_953830641908440E9CDBB34495FCE15B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_35044AD4F4124CD09889FC18364F31C7 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D3EA4D341C77481EA8CEAE97E4D37DE8 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'waterloo'
          slot-name: 'Production'
          package: ./output/API