name: .NET Deploy

on:
  push:
    branches: [ "main" ]
    
permissions:
  contents: read
  actions: read
  checks: write

jobs:
  build:
    name: .NET Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
         dotnet-version: '9.x'

    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: dotnet publish
      run: dotnet publish ./Waterloo/Waterloo.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp /p:DeleteExistingFiles=true

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: .net-app
        path: ${{env.DOTNET_ROOT}}/myapp
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    if: github.event_name == 'push'
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_953830641908440E9CDBB34495FCE15B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_35044AD4F4124CD09889FC18364F31C7 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D3EA4D341C77481EA8CEAE97E4D37DE8 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'waterloo'
          slot-name: 'Production'
          package: .